/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capstone.gui;

import capstone.CapException;
import capstone.gui.UsefulReviewSelect.ChangeVotesListener;
import capstone.testsuite.TestSuite;
import capstone.yelpmodel.ARFFWriter;
import capstone.yelpmodel.Business;
import capstone.yelpmodel.Review;
import capstone.yelpmodel.YelpModel;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONObject;

/**
 *
 * @author mark
 */
public class MainGUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainGUIPanel
     */
    public MainGUIPanel() {
        initComponents();
        
        businessSelectView.addListSelectionListener(businessListUpdate);
        usefulReviewSelection.addListener(helpfulLabelUpdate);
    }
    private ChangeVotesListener helpfulLabelUpdate = new ChangeVotesListener() {
            public void votesChange(long newVotes) {
                helpfulVotesLabel.setText("Reviews with 'helpful' votes >= " + newVotes);
            }
        };
    private ListSelectionListener businessListUpdate = new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    businessSelected(lse);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };

    private CapstoneApplication app;
    MainGUIPanel(CapstoneApplication app) {
        super();
        this.app = app;
        initComponents();
        businessSelectView.addListSelectionListener(businessListUpdate);
        usefulReviewSelection.addListener(helpfulLabelUpdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        businessCategorySelection = new javax.swing.JComboBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        businessSelectView = new capstone.gui.DataSetView();
        jSONDetailView1 = new capstone.gui.JSONDetailView();
        jPanel7 = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uselessReviewSelection = new capstone.gui.DataSetView();
        jPanel5 = new javax.swing.JPanel();
        helpfulVotesLabel = new javax.swing.JLabel();
        usefulReviewSelection = new capstone.gui.UsefulReviewSelect();
        jSONDetailView2 = new capstone.gui.JSONDetailView();
        jPanel10 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        testSuiteGUISelect1 = new capstone.gui.TestSuiteGUISelect();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        trainingSetResults = new capstone.gui.ResultTable();
        jPanel9 = new javax.swing.JPanel();
        testSetResults = new capstone.gui.ResultTable();
        jButton2 = new javax.swing.JButton();
        exportButtonTestWRFF = new javax.swing.JButton();
        exportButtonTrainingWRFF = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        businessCategorySelection.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        businessCategorySelection.setMinimumSize(new java.awt.Dimension(64, 64));
        businessCategorySelection.setPreferredSize(new java.awt.Dimension(64, 64));
        businessCategorySelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                businessCategorySelectionEvent(evt);
            }
        });
        businessCategorySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessCategorySelectionActionPerformed(evt);
            }
        });
        jPanel1.add(businessCategorySelection, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        businessSelectView.setSortKey("review_count");
        businessSelectView.setSorted(true);
        jSplitPane1.setLeftComponent(businessSelectView);
        jSplitPane1.setRightComponent(jSONDetailView1);

        jSONDetailView1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jSplitPane1.setRightComponent(jSONDetailView1);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel7.setMaximumSize(new java.awt.Dimension(64, 64));
        jPanel7.setPreferredSize(new java.awt.Dimension(64, 64));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capstone/gui/go-next.png"))); // NOI18N
        nextButton.setText("Select Review Sets");
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Select Business", jPanel1);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(320);
        jSplitPane2.setDividerSize(8);
        jSplitPane2.setResizeWeight(0.5);
        jSplitPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jSplitPane2ComponentResized(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(128, 128, 128));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reviews without 'helpful' votes");
        jLabel1.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel1.setOpaque(true);

        uselessReviewSelection.setKeys(new String[] {"text"});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uselessReviewSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uselessReviewSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel4);

        helpfulVotesLabel.setBackground(new java.awt.Color(128, 128, 128));
        helpfulVotesLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        helpfulVotesLabel.setForeground(new java.awt.Color(0, 0, 0));
        helpfulVotesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpfulVotesLabel.setText("Reviews with ? helpful votes");
        helpfulVotesLabel.setMinimumSize(new java.awt.Dimension(32, 32));
        helpfulVotesLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usefulReviewSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
            .addComponent(helpfulVotesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpfulVotesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usefulReviewSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel5);

        jPanel6.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSONDetailView2.setPreferredSize(new java.awt.Dimension(96, 96));
        jPanel6.add(jSONDetailView2, java.awt.BorderLayout.PAGE_START);

        jButton3.setText("Export Test Data File (Unvoted)");

        jButton4.setText("Export Training Data File (Voted useful)");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capstone/gui/go-next.png"))); // NOI18N
        jButton5.setText("Examine Text Features");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Business Reviews", jPanel2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainingSetResults, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainingSetResults, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Training set (voted helpful)", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testSetResults, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testSetResults, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Test set (not voted helpful)", jPanel9);

        jButton2.setText("Run tests");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exportButtonTestWRFF.setText("Export Test ARFF file...");
        exportButtonTestWRFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonTestWRFFActionPerformed(evt);
            }
        });

        exportButtonTrainingWRFF.setText("Export Training ARFF file...");
        exportButtonTrainingWRFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonTrainingWRFFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testSuiteGUISelect1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exportButtonTestWRFF, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportButtonTrainingWRFF, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testSuiteGUISelect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportButtonTrainingWRFF, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(exportButtonTestWRFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Select Review Tests", jPanel3);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void businessCategorySelectionEvent(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_businessCategorySelectionEvent
        if (evt.getItem() == null) return;
        
        try {
            Business bus = model.getBusinesses();
            bus = bus.trimByCategory(new String[] { (String)evt.getItem() });
            businessSelectView.setModel(bus);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_businessCategorySelectionEvent

    private void businessCategorySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessCategorySelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_businessCategorySelectionActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        int thisTab = jTabbedPane1.getSelectedIndex();
        if (thisTab + 1 < jTabbedPane1.getTabCount()) thisTab++;
        jTabbedPane1.setSelectedIndex(thisTab);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        TestSuite genSuite = this.testSuiteGUISelect1.generateTestSuite();
        if (genSuite == null) return;
        
        Review testSet = (Review) uselessReviewSelection.getModel();
        Review trainSet = usefulReviewSelection.getUsefulModel();
        
        testSetResults.generateModel(genSuite, testSet);
        trainingSetResults.generateModel(genSuite, trainSet);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jSplitPane2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSplitPane2ComponentResized
        jSplitPane2.setDividerLocation(0.5);
    }//GEN-LAST:event_jSplitPane2ComponentResized

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void exportButtonTestWRFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonTestWRFFActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Export Test WRFF file");
        jfc.setSelectedFile(new File("test.arff"));
        jfc.setFileFilter(new FileNameExtensionFilter("ARFF File", "arff"));
        
        if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            FileOutputStream fos = null;

            try {
                ARFFWriter writer = new ARFFWriter(f.getName(), testSetResults.getModel());
                fos = new FileOutputStream(f);
                writer.writeToStream(fos);
                fos.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            } finally {
            }
            
        }
        
    }//GEN-LAST:event_exportButtonTestWRFFActionPerformed

    private void exportButtonTrainingWRFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonTrainingWRFFActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Export Training WRFF file");
        jfc.setSelectedFile(new File("training.arff"));
        jfc.setFileFilter(new FileNameExtensionFilter("ARFF File", "arff"));
        
        if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            FileOutputStream fos = null;

            try {
                ARFFWriter writer = new ARFFWriter(f.getName(), trainingSetResults.getModel());
                fos = new FileOutputStream(f);
                writer.writeToStream(fos);
                fos.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            } finally {
            }
        }
    }//GEN-LAST:event_exportButtonTrainingWRFFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox businessCategorySelection;
    private capstone.gui.DataSetView businessSelectView;
    private javax.swing.JButton exportButtonTestWRFF;
    private javax.swing.JButton exportButtonTrainingWRFF;
    private javax.swing.JLabel helpfulVotesLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private capstone.gui.JSONDetailView jSONDetailView1;
    private capstone.gui.JSONDetailView jSONDetailView2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton nextButton;
    private capstone.gui.ResultTable testSetResults;
    private capstone.gui.TestSuiteGUISelect testSuiteGUISelect1;
    private capstone.gui.ResultTable trainingSetResults;
    private capstone.gui.UsefulReviewSelect usefulReviewSelection;
    private capstone.gui.DataSetView uselessReviewSelection;
    // End of variables declaration//GEN-END:variables

    
    private YelpModel model = null;
    void modelIsLoaded(YelpModel model) {
        this.model = model;
        
        businessCategorySelection.setModel(app.getAllBusinessCategories());
    }
    
    public void businessSelected(ListSelectionEvent lse) throws CapException {

        uselessReviewSelection.setModel(null);
        usefulReviewSelection.setModel(null);
        
        JSONObject obj;
        if ((obj = businessSelectView.getSelected()) == null) return;

        String businessID = (String)(obj.get("business_id"));
        Review rSet = model.getReviews().getReviewsForBusiness(businessID);
    
        uselessReviewSelection.setModel(rSet.trimByVotes("useful", -1));
        usefulReviewSelection.setModel(rSet);

        String ignoreKeys[] = new String[] {
            "type", "state", "open", "neighborhoods", "latitude", "longitude"
        };
        
        jSONDetailView1.addIgnoreKeys(ignoreKeys);
        jSONDetailView1.setModel(obj);
        jSONDetailView2.addIgnoreKeys(ignoreKeys);
        jSONDetailView2.setModel(obj);
    }
    
}
